#!/bin/sh
#
# Devfs handling script.  Since we arent running devfsd due to various reasons
# which I will not lay out here, we need to create some links for compatibility.

. /etc/default/rcS

# exit without doing anything if udev is active
if test -e /dev/.udev -o -e /dev/.udevdb; then
	exit 0
fi


if ! grep -q ' /dev ' /proc/mounts
then
	if test "$VERBOSE" != "no"; then echo -n "Mounting /dev ramdisk: "; fi
	mount -t ramfs ramfs /dev || mount -t tmpfs ramfs /dev
	if test $? -ne 0; then
		if test "$VERBOSE" != "no"; then echo "failed"; fi
	else
		if test "$VERBOSE" != "no"; then echo "done"; fi
	fi
fi
if test "$VERBOSE" != "no"; then echo -n "Populating /dev: "; fi
cd /
mkdir -p dev/input
mkdir -p dev/msys
mkdir -p dev/pts
mkdir -p dev/vc
mkdir -p dev/snd
for i in 0 1 2 3 4 5 6 7 8 9; do
	ln -s /dev/tty$i /dev/vc/$i
done
ln -sf /proc/self/fd /dev/fd
ln -sf /proc/kcore /dev/core

if test `readlink -f "/sbin/makedevs"` = "/bin/busybox"; then
	MAKEDEV_ARGS="-d /etc/device_table /"
else
	MAKEDEV_ARGS="-r / -D /etc/device_table"
fi
/sbin/makedevs $MAKEDEV_ARGS
if test $? -ne 0; then
	if test "$VERBOSE" != "no"; then echo "failed"; fi
else
	if test "$VERBOSE" != "no"; then echo "done"; fi
fi

exit 0
