#! /bin/sh 
#
# This is an init script for openembedded
# Copy it to /etc/init.d/samba and type
# > update-rc.d samba defaults 60
#


nmbd=/usr/sbin/nmbd
test -x "$nmbd" || exit 0
CONFIG_FILE="/etc/samba/smb.conf"


case "$1" in
  start)
    echo -n "Starting Samba: nmbd"
    start-stop-daemon --start --quiet --exec $nmbd -- -s $CONFIG_FILE
    echo "."
    ;;
  stop)
    echo -n "Stopping Samba: nmbd"
    start-stop-daemon --stop --quiet --pidfile /var/run/nmbd.pid
    echo "."
    ;;
  reload|force-reload)
    start-stop-daemon --stop --quiet --signal 1 --exec $nmbd -- -s $CONFIG_FILE
    ;;
  restart)
    echo -n "Stopping Samba: nmbd"
    start-stop-daemon --stop --quiet --pidfile /var/run/nmbd.pid
    echo ""
    echo -n "Waiting for samba processes to die off"
    for i in 1 2 3 ;
    do
        sleep 1
        echo -n "."
    done
    echo ""
    echo -n "Starting Samba: nmbd"
    start-stop-daemon --start --quiet --exec $nmbd -- -s $CONFIG_FILE
    echo "."
    ;;
  *)
    echo "Usage: /etc/init.d/samba {start|stop|reload|restart|force-reload}"
    exit 1
esac

exit 0
